### ISSUE TITLE
Goal Destionation Orientation Change

### ISSUE THREAD

**Issue by aarontan94** [gkouros/waypoint-global-planner#2]
Hello,

Another question, I noticed that the robot tries to make a 180 degree change in orientation when it reaches the goal destination.

For example, as it reaches the goal destination, it'll turn around and back in to the goal point. Instead of facing towards the direction of the goal point, the heading angle changes to face where the robot's initial pose is.

Do you know how I can change this so that it doesn't make this 180 degree change at the goal destination?

Thanks,
Aaron

**Comment by gkouros** [comment]
The final goal pose orientation is based on the orientation between the two last waypoints.
So when you click the final waypoint do it close to the previous one and towards the direction
you want to end up in. Also, visualize the final goal pose in rviz via the topic: /move_base_simple/goal
to have a clear view of the final goal orientation.

If your issue still happens anyway, there may be something wrong with your local planner.

**Comment by aarontan94** [comment]
@gkouros I see.

If I want to set predefined way points in the code so that I am not relying on the accuracy of my mouse clicks, do you have any recommendations on how I can achieve that with your repo?

Thanks!
Aaron

**Comment by gkouros** [comment]
There are a few different ways:

1) Make a script/node that loads the waypoints from a yaml file and then constructs and
publishes a nav_msgs::Path message to the topic /move_base/WaypointGlobalPlanner/external_path.

2) write a script/node that loads the waypoints from a yaml file and for each waypoint it publishes
it in a geometry_msgs/PointsStamped message to the topic /clicked_point

3) (SLOW) Write a bash script that publishes the points at /clicked_point topic using the rostopic command
```
rostopic pub -1 /clicked_point geometry_msgs/PointStamped "{
  header: [0, 0, map],
  point: [3, 5, 0]
  }"
```

**Comment by aarontan94** [comment]
I am new to ROS, could you provide some more hints regarding the first way?
