### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by Minsu-Kim1822** [gkouros/waypoint-global-planner#9]
Hi, I'm trying to use this package for simulation..

1. Is this package required cost map such as 2d gridmap?
2. I typed 
<rosparam file="$(find waypoint_global_planner)/config/base_global_planner_params.yaml" command="load" ns="move_base" />

in my steer_bot_sim.lauch file, but it does not work.

May I ask for a help?

**Comment by gkouros** [comment]
It does require a costmap. It works like any other global planner, so if your setup works with e.g. [global_planner](http://wiki.ros.org/global_planner) it should work with waypoing\_global\_planner. 

You didn't specify, what exact error are you facing?
